#!/bin/bash
# Exemplo de uso do Token Ring
# Este script testa a comunicação entre 3 máquinas

clear
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║         TOKEN RING - Exemplo de Uso - 3 Máquinas                  ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Este exemplo demonstra como usar o Token Ring com 3 máquinas: A, B, C"
echo ""
echo "Pré-requisitos:"
echo "  - Compilar: make"
echo "  - 3 terminais diferentes"
echo ""
echo "Passos:"
echo ""
echo "1️⃣  TERMINAL 1 - Máquina A:"
echo "   $ ./ring_network config_A.txt"
echo ""
echo "   Você verá:"
echo "   [14:32:15] Rede inicializada: A em 192.168.1.100"
echo "   [14:32:15] DISCOVER enviado: 10:A:192.168.1.100"
echo "   [14:32:16] Anel reconstruído: A (próximo: A)"
echo "   [14:32:18] TOKEN INICIAL GERADO"
echo ""
echo "2️⃣  TERMINAL 2 - Máquina B (abrir novo terminal):"
echo "   $ cd /home/ana/Fund_Redes"
echo "   $ ./ring_network config_B.txt"
echo ""
echo "   Em TERMINAL 1 você verá:"
echo "   [14:32:20] HELLO recebido de B (192.168.1.101)"
echo "   [14:32:20] Nova máquina adicionada: B"
echo "   [14:32:20] Anel reconstruído: A B (próximo: B)"
echo ""
echo "3️⃣  TERMINAL 3 - Máquina C (abrir novo terminal):"
echo "   $ cd /home/ana/Fund_Redes"
echo "   $ ./ring_network config_C.txt"
echo ""
echo "   Em TERMINAL 1 você verá:"
echo "   [14:32:22] HELLO recebido de C (192.168.1.103)"
echo "   [14:32:22] Nova máquina adicionada: C"
echo "   [14:32:22] Anel reconstruído: A B C (próximo: B)"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                         TESTE 1: Topologia"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Em TERMINAL 1 (Máquina A), digite:"
echo "  > r"
echo ""
echo "Resultado esperado:"
echo "  Anel atual (3 máquinas): A B C"
echo "  Máquina atual: A (índice 0), próximo: B (índice 1)"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                    TESTE 2: Status do Token"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Em TERMINAL 1, digite:"
echo "  > t"
echo ""
echo "Resultado esperado:"
echo "  Token status: has=1, count=1, total_gerados=1"
echo ""
echo "Em TERMINAL 2, digite:"
echo "  > t"
echo ""
echo "Resultado esperado:"
echo "  Token status: has=0, count=1, total_gerados=0"
echo ""
echo "Nota: O token circula continuamente!"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                  TESTE 3: Enviar Mensagem (A → B)"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Em TERMINAL 1 (Máquina A), digite:"
echo "  > s B Olá B, como vai?"
echo ""
echo "Logs esperados em TERMINAL 1:"
echo "  [14:35:30] Mensagem enfileirada para B: Olá B, como vai?"
echo "  [14:35:32] TOKEN recebido!"
echo "  [14:35:33] Transmitindo mensagem de fila para B"
echo "  [14:35:33] DATA enviada: 2000:A:B:maquinainexistente:2945738291:Olá B, como vai?"
echo ""
echo "Logs esperados em TERMINAL 2 (Máquina B):"
echo "  [14:35:33] TOKEN recebido!"
echo "  [14:35:33] DATA recebida de A: Olá B, como vai?"
echo "  [14:35:33] CRC: esperado=2945738291, calculado=2945738291"
echo "  [14:35:33] Resposta ACK encaminhada"
echo ""
echo "Logs esperados em TERMINAL 1 (depois):"
echo "  [14:35:35] TOKEN recebido!"
echo "  [14:35:35] DATA recebida de A: (resposta)"
echo "  [14:35:35] Resposta ACK encaminhada"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                  TESTE 4: Topologia Dinâmica"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Agora adicionar máquina D!"
echo ""
echo "Em TERMINAL 4 (novo), digite:"
echo "  $ cd /home/ana/Fund_Redes"
echo "  $ ./ring_network config_D.txt"
echo ""
echo "Você verá em todos os terminais:"
echo "  [14:35:50] DISCOVER recebido de D"
echo "  [14:35:50] Nova máquina adicionada: D"
echo "  [14:35:50] Anel reconstruído: A B C D (próximo: ...)"
echo ""
echo "Ver novo anel:"
echo "  > r"
echo ""
echo "Resultado:"
echo "  Anel atual (4 máquinas): A B C D"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "              TESTE 5: Múltiplas Mensagens e Circulação"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Em TERMINAL 1 (A), faça 3 mensagens:"
echo "  > s B Primeiro"
echo "  > s C Segundo"
echo "  > s B Terceiro"
echo ""
echo "Observar:"
echo "  - Mensagens enfileiradas (fila = 3/10)"
echo "  - Após token chegar em A:"
echo "    * Envia primeira para B"
echo "    * Passa token para B"
echo "    * B não tem mensagens, passa para C"
echo "    * C não tem mensagens, passa para A"
echo "    * A envia segunda para C"
echo "    * ... e assim por diante"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                     COMANDOS DISPONÍVEIS"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "  s <destino> <mensagem>  - Enviar mensagem"
echo "    Exemplo: s B Olá B!"
echo "    Máximo: 10 mensagens na fila"
echo ""
echo "  r                        - Ver anel"
echo "    Mostra: máquinas ativas, índice atual, próximo"
echo ""
echo "  t                        - Token status"
echo "    Mostra: tenho token?, quantos tokens, total gerados"
echo ""
echo "  q                        - Sair"
echo "    Encerra a máquina"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                        DICAS E TRUQUES"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Enviar para máquina que não existe:"
echo "   > s X teste"
echo "   Resultado: 'Máquina não existe na rede'"
echo ""
echo "2. Ver logs em tempo real:"
echo "   - Todos os eventos têm timestamp [HH:MM:SS]"
echo "   - Procurar por:"
echo "     * 'TOKEN recebido' - máquina tem token"
echo "     * 'DATA recebida' - mensagem chegou"
echo "     * 'Resposta ACK' - confirmação de sucesso"
echo "     * 'Resposta NAK' - erro na transmissão"
echo ""
echo "3. Monitorar passagem de token:"
echo "   - Em uma máquina, digitar 't' cada 2 segundos"
echo "   - Ver has=1 (tenho token), depois has=0 (passou)"
echo ""
echo "4. Testar fila cheia:"
echo "   - Enviar 11 mensagens (máximo é 10)"
echo "   - Última dará erro"
echo ""
echo "5. Simular máquina lenta:"
echo "   - Editar token_time em config_X.txt"
echo "   - Aumentar tempo entre transmissões"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                      INTERPRETANDO LOGS"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "[14:32:15] Timestamp"
echo "├─ Hora local (HH:MM:SS)"
echo "└─ Sincronizado com sistema"
echo ""
echo "[14:32:16] Anel reconstruído: A B (próximo: B)"
echo "├─ Topologia mudou"
echo "├─ Máquinas ativas: A B"
echo "└─ Próxima máquina será B"
echo ""
echo "[14:32:18] TOKEN INICIAL GERADO"
echo "├─ Máquina A iniciou o token"
echo "├─ Começa a circular"
echo "└─ Outras máquinas podem enviar mensagens"
echo ""
echo "[14:35:33] DATA enviada: 2000:A:B:maquinainexistente:...:Olá!"
echo "├─ Tipo 2000 (pacote de dados)"
echo "├─ De A para B"
echo "├─ Status inicial: 'maquinainexistente'"
echo "├─ CRC: checksum da mensagem"
echo "└─ Conteúdo: 'Olá!'"
echo ""
echo "[14:35:33] DATA recebida de A: Olá!"
echo "├─ Mensagem chegou em B"
echo "├─ Origem: A"
echo "└─ Conteúdo: 'Olá!'"
echo ""
echo "[14:35:33] CRC: esperado=..., calculado=..."
echo "├─ Se iguais: mensagem OK"
echo "├─ Se diferentes: houve erro na transmissão"
echo "└─ Status será NAK (solicitação de retransmissão)"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                    POSSÍVEIS PROBLEMAS"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "❌ Problema: \"cannot bind port\""
echo "✅ Solução: Porta já em uso"
echo "   - Mudar em common.h (#define DISCOVER_PORT 6000)"
echo "   - Recompilar: make clean && make"
echo ""
echo "❌ Problema: \"cannot open socket\""
echo "✅ Solução: Problema de permissão"
echo "   - Tentar sem sudo primeiro"
echo "   - Se não funcionar, verificar firewall"
echo ""
echo "❌ Problema: Token não circula"
echo "✅ Solução: Máquina A pode não ter iniciado"
echo "   - Sempre iniciar A primeiro"
echo "   - Ou esperar alguns segundos"
echo ""
echo "❌ Problema: DISCOVER não é visto"
echo "✅ Solução: Firewall bloqueando UDP porta 6000"
echo "   - Desabilitar temporariamente"
echo "   - Ou permitir portas 6000-6001"
echo ""
echo "❌ Problema: Mensagem não chega"
echo "✅ Solução: Destino pode não estar no anel"
echo "   - Digitar 'r' para ver topologia"
echo "   - Garantir que máquina destino iniciou"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "                    PRONTO PARA COMEÇAR? 🚀"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Próximo passo:"
echo ""
echo "1. Abra 3 terminais diferentes"
echo ""
echo "2. Terminal 1:"
echo "   $ cd /home/ana/Fund_Redes"
echo "   $ ./ring_network config_A.txt"
echo ""
echo "3. Terminal 2:"
echo "   $ cd /home/ana/Fund_Redes"
echo "   $ ./ring_network config_B.txt"
echo ""
echo "4. Terminal 3:"
echo "   $ cd /home/ana/Fund_Redes"
echo "   $ ./ring_network config_C.txt"
echo ""
echo "5. Em Terminal 1, teste com:"
echo "   > r        (ver anel)"
echo "   > s B Oi!  (enviar)"
echo "   > q        (sair)"
echo ""
echo "Boa sorte! 🍀"
echo ""
